meta:
  environment: riemann-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: riemann
    networks:
      - name: riemann1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: riemann1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.26.0/30
    reserved:
    - 10.244.26.1
    static:
    - 10.244.26.2

  - cloud_properties:
      name: random
    range: 10.244.26.4/30
    reserved:
    - 10.244.26.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.26.8/30
    reserved:
    - 10.244.26.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.26.12/30
    reserved:
    - 10.244.26.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.26.16/30
    reserved:
    - 10.244.26.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.26.20/30
    reserved:
    - 10.244.26.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.26.24/30
    reserved:
    - 10.244.26.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.26.28/30
    reserved:
    - 10.244.26.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.26.32/30
    reserved:
    - 10.244.26.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.26.36/30
    reserved:
    - 10.244.26.37
    static: []
